# Refactored customizations
title: 'the missing semester of your cs education'
url: https://www.cs.uic.edu/~ckanich/missing/
repository: https://github.com/kaytwo/missing-semester
ckanich: https://www.cs.uic.edu/~ckanich/
email: ckanich@uic.edu
youtube: https://www.youtube.com/playlist?list=PLyzOVJj3bHQuloKGG59rS43e29ro7I57J
offering: f20

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/Chicago
analytics:
  tracking_id: UA-21532225-1

collections:
  'f20':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
